### ISSUE TITLE
Create LA Devs mission statement

### ISSUE THREAD

**Issue by j-sm-n** [la-devs/issue-tracking#8]
_For some inspiration_ 👇 

From Denver Devs meta description:
> We are a Denver, Colorado based software engineer community focused on helping each other find jobs, solve problems, make friends, and so much more. We’re on Slack and Discourse.

From Denver Devs landing page:
> We're a community focused on helping each other find jobs, solve problems, make friends, and so much more.

**Comment by rdavid1099** [comment]
We are an inclusive, Los Angeles based technology community focused on helping each other grow through knowledge sharing and friendships.
